// <auto-generated />
namespace InfoColeAplicacion.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class Noticias90 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Noticias90));
        
        string IMigrationMetadata.Id
        {
            get { return "201811042210398_Noticias90%"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
